=== maqutadir/IS7024_groupproject/FinalGroupProject/FinalGroupProject/mickeyfriends.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="friends">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="friend" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="name" type="xs:string"/>
              <xs:element name="species"  type="xs:string"/>
              <xs:element name="gender" minOccurs="0">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:enumeration value="female"/>
                    <xs:enumeration value="male"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="about" minOccurs="0">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:maxLength value="500"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== maqutadir/IS7024_groupproject/FinalGroupProject/FinalGroupProject/mickeyfriends.xml
<?xml version="1.0" encoding="utf-8" ?>
<?xml-stylesheet type="text/xsl" href="mickeyfriends.xsl"?>
<friends xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="mickeyfriends.xsd">
  <friend>
    <name>Mickey Mouse</name>
    <species>mouse</species>
    <gender>male</gender>
    <about>Mickey Mouse loves adventure and trying new things, though his best intentions often go awry. He is optimistic and a friend to everyone.</about>
  </friend>
  <friend>
    <name>Minnie Mouse</name>
    <species>mouse</species>
    <gender>female</gender>
    <about>Minnie Mouse is sweet, stylish, and enjoys dancing and singing. She especially loves to spend time with her lifelong sweetheart, Mickey.</about>
  </friend>
  <friend>
    <name>Goofy</name>
    <species>dog</species>
    <gender>male</gender>
    <about>Goofy is good-natured. Though he can be a bit clumsy and trips himself up from time to time, he never loses his willingness to try his best at anything.</about>
  </friend>
  <friend>
    <name>Pluto</name>
    <species>dog</species>
    <gender>male</gender>
    <about>Fun-loving, curious, and playful, Pluto has the heart of a puppy. He is a very loyal companion to Mickey.</about>
  </friend>
  <friend>
    <name>Donald Duck</name>
    <species>duck</species>
    <gender>male</gender>
    <about>Donald Duck might be quick-tempered when things don't go his way, but he has a heart of gold and is very devoted to his friends.</about>
  </friend>
  <friend>
    <name>Daisy Duck</name>
    <species>duck</species>
    <gender>female</gender>
    <about>Daisy Duck is a friend to many and is Minnie's best friend. While she can be sassy, she's always sweet to those she cares about, especially her guy, Donald.</about>
  </friend>
</friends>
